
version: "3"

services:
  web:
    build: .
    command: /start-reload.sh
    volumes:
      - ./:/app
    ports:
      - "80:80"
  mongo:
    image: mongo
    volumes:
      - data:/data/db

volumes:
  data: # persistent mongo data